#!/bin/bash

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
dbuser=$(ynh_app_setting_get "$app" dbuser)
dbname=$(ynh_app_setting_get "$app" dbname)
# dbpass=$(ynh_app_setting_get "$app" dbpass)

ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true

sudo rm -rf /var/www/$app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
sudo rm -rf /var/log/$app

sudo service php5-fpm restart
sudo service nginx reload
